# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93002ac6b1e50adf93d5d63ed83e0ed779963fb0cd71c466eec5cf75d43cb72b1629d8c7ab3dc71af8c90fb2825b1b47ed4adaec40c9c7bd1397b46b17649224

test:
  secret_key_base: 90d41ce50486e07217f174e8099f933862845bd887a9fb8266fd738889f1a4e420f45e117dd76e7728054dec4ee9ff1ccc3a99a43a6440fca6d881f4e144f16d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
